[project]
name = "hda-project-2023"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keras-tuner>=1.4.7",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "scikeras>=0.13.0",
    "scikit-learn>=1.7.2",
    "tensorflow>=2.20.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "ipython>=9.7.0",
    "matplotlib>=3.10.7",
    "pre-commit>=4.4.0",
]

[tool.uv.sources]
hda = { path = "./hda" }
